cloud:
    aws:
        credentials:
            access-key:
            secret-key:
        region:
            auto: false
            static: ap-south-1
            use-default-aws-region-chain: true
        stack: false
        stack.auto: false
logging:
    level:
        com:
            amazonaws:
                internal:
                    InstanceMetadataServiceResourceFetcher: error
                util:
                    EC2MetadataUtils: error
